// vue-app/src/components/Form.vue
<template>
    <form>
        <div v-for="movie in movies" :key="movie.index">
            <img :src="movie.img" :alt="movie.title">
            <div>
                <h3>{{ movie.title }}</h3>
                <button type="button" @click="removeMovieQuantity(movie.title)" :disabled="movie.quantity <= 0">-</button>
                {{ movie.quantity }}
                <button type="button" @click="addMovieQuantity(movie.title)" :disabled="movie.quantity >= movie.ticketsAvailable">+</button>
            </div>
        </div>
    </form>
</template>

<script>
export default {
    name: "Form",
    props: ["movies"],

    // We can also create methods in the component
    methods: {
        addMovieQuantity(movieName) {
            this.movies.forEach(movie => {
                if (movie.title === movieName) {
                movie.quantity += 1;
                }
            });
        },

        removeMovieQuantity(movieName) {
            this.movies.forEach(movie => {
                if (movie.title === movieName) {
                    movie.quantity -= 1;
                }
            });
        }
    }
}

</script>

<style scoped>
    form > div {
        background-color: #333333;
        border-radius: 20px;
        display: grid;
        font-size: clamp(1.5rem, 2vw, 2.5rem);
        grid-template-columns: 40% 60%;
        grid-gap: 10px;
        margin: 20px auto;
        max-width: 800px;
        overflow: hidden;
        place-items: center center;
    }

    h3 {
        margin-bottom: 10px;
        font-size: clamp(2rem, 4vw, 3rem);
    }

    img {
        object-fit: cover;
        width: 100%;
    }

    button {
        background-color: #42b883 ;
        border: none;
        color: #fff;
        font-size: clamp(1.5rem, 4vw, 2rem);
        transition: all 0.2s ease-in-out;
        padding: 10px 20px;
    }

    button:hover {
        transform: scale(1.1);
    }

    button:active {
        transform: scale(0.9) translateY(2px);
    }

    button:disabled {
        opacity: 0.5;
        pointer-events: none;
    }
</style>

// react-app/src/components/Form.js
import { useState } from "react";
import styled from "styled-components";
import SubTitle from "./SubTitle";
import Button from "./Button";

export default function Form({ movie, updateTheme }) {
	const [quantity, setQuantity] = useState(0);

	return (
		<StyledForm onMouseEnter={() => updateTheme()}>
			<StyledImg src={movie.img} alt={movie.title} />
			<div>
				<SubTitle>{movie.title}</SubTitle>
				<Button
					type="button"
					onClick={() => {
						setQuantity(quantity - 1);
					}}
					disabled={quantity <= 0}
				>
					-
				</Button>
				{quantity}
				<Button
					type="button"
					onClick={() => {
						setQuantity(quantity + 1);
					}}
					disabled={quantity >= movie.ticketsAvailable}
				>
					+
				</Button>
			</div>
		</StyledForm>
	);
}

const StyledForm = styled.form`
	background-color: ${(props) => props.theme.bg};
	border-radius: 20px;
	box-shadow: 0px 0px 5px 2px rgba(0, 0, 0, 0.1);
	color: ${(props) => props.theme.color};
	display: grid;
	font-size: clamp(1.5rem, 2vw, 2.5rem);
	grid-template-columns: 40% 60%;
	grid-gap: 10px;
	margin: 20px auto;
	max-width: 800px;
	overflow: hidden;
	place-items: center center;
	transition: all 0.1s ease-in-out;
`;

const StyledImg = styled.img`
	object-fit: cover;
	width: 100%;
`;
